[config]
schemaVersion = "0.0.1"

[package]
namespace = "xhayper"
name = "NoFollowerLevelLimit"
versionNumber = "1.0.4"
description = "Remove follower level limit"
websiteUrl = "https://github.com/xhayper/NoFollowerLevelLimit"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_CultOfTheLamb = "5.4.21"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "bin/Release/NoFollowerLevelLimit/NoFollowerLevelLimit.dll"
target = "plugins/io.github.xhayper.NoFollowerLevelLimit/NoFollowerLevelLimit.dll"

[publish]
repository = "https://cult-of-the-lamb.thunderstore.io"
communities = ["cult-of-the-lamb"]
categories = ["misc"]